# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'DatabaseFetch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DatabaseFetch
  pod 'GooglePlaces', '6.0.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'SwiftyJSON'

end
